// Generated by https://quicktype.io

export interface ComentarioObtenerResponseI {
  post: Post[];
}

export interface Post {
  id:         number;
  comentario: string;
  post_id:    number;
  state:      boolean;
  user_id:    number;
  user:       User;
}

export interface User {
  id:       number;
  user:     string;
  password: string;
  email:    string;
  state:    boolean;
}
export interface createComentarioI{
  comentario:string,
  post_id:number,
  user_id:number
}

// Generated by https://quicktype.io

export interface CreateComentarioResponseI {
  message:    string;
  newComment: NewComment;
}

export interface NewComment {
  state:      boolean;
  id:         number;
  comentario: string;
  post_id:    number;
  user_id:    number;
}
